title: Nagornov Yuri / Iurii
logo: /assets/img/Photo-23.jpg
description: I am Researcher at the National Cancer Center Japan, Division of Bioinformatics.
show_downloads: true
theme: jekyll-theme-minimal
